/**
 * Type declarations for the valrs-wasm module.
 *
 * This module is built from Rust using wasm-pack and provides the
 * core validation functionality. These declarations allow TypeScript
 * to understand the module structure before it's built.
 */

declare module 'valrs-wasm' {
  /**
   * Default initialization function for the WASM module.
   * This is generated by wasm-pack for web targets.
   */
  export default function init(): Promise<void>;

  /**
   * Validation result from WASM functions.
   */
  interface WasmResult {
    value?: unknown;
    issues?: Array<{
      message: string;
      path?: Array<string | number>;
    }>;
  }

  // Primitive validation functions
  export function validateString(value: unknown): WasmResult;
  export function validateNumber(value: unknown): WasmResult;
  export function validateBoolean(value: unknown): WasmResult;
  export function validateI32(value: unknown): WasmResult;
  export function validateI64(value: unknown): WasmResult;
  export function validateU32(value: unknown): WasmResult;
  export function validateU64(value: unknown): WasmResult;
  export function validateF32(value: unknown): WasmResult;
  export function validateF64(value: unknown): WasmResult;

  // JSON Schema generation functions
  export function stringJsonSchema(target: string): Record<string, unknown>;
  export function numberJsonSchema(target: string): Record<string, unknown>;
  export function booleanJsonSchema(target: string): Record<string, unknown>;
  export function i32JsonSchema(target: string): Record<string, unknown>;
  export function i64JsonSchema(target: string): Record<string, unknown>;
  export function u32JsonSchema(target: string): Record<string, unknown>;
  export function u64JsonSchema(target: string): Record<string, unknown>;
  export function f32JsonSchema(target: string): Record<string, unknown>;
  export function f64JsonSchema(target: string): Record<string, unknown>;

  // Array and object validation (for future use)
  export function validateArray(
    value: unknown,
    itemValidator: (item: unknown) => WasmResult
  ): WasmResult;
  export function arrayJsonSchema(
    itemSchema: Record<string, unknown>,
    target: string
  ): Record<string, unknown>;
}
